[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris" 
optimizer = true
optimizer_runs = 2_000

[rpc_endpoints]
core = "https://rpc.ankr.com/core"
gnosis = "https://rpc.ankr.com/gnosis"
celo = "https://rpc.ankr.com/celo"